<template>
  <div id="app">
    <svg-msa :seqs="seqs2" coloring="metadata"></svg-msa>
    <svg-msa :start="start" :end="end" :seqs="seqs" :tracks="testTracks" coloring="auto"></svg-msa>
  </div>
</template>

<script>
import SvgMsa from './components/SvgMsa/SvgMsa.vue';

export default {
  name: 'App',
  components: {
    SvgMsa
  },
  data() {
    return {
      start: 18,
      end: 40,
      seqs: [
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC-AT',
          id: 'seqid1',
          name: 'seq1'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC',
          id: 'seqid2',
          name: 'seq2'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC-AT',
          id: 'seqid3',
          name: 'seq3'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC',
          id: 'seqid4',
          name: 'seq4'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC-AT',
          id: 'seqid5',
          name: 'seq5'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC',
          id: 'seqid6',
          name: 'seq6'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC-AT',
          id: 'seqid7',
          name: 'seq7'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCACGCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATC',
          id: 'seqid8',
          name: 'seq8'
        }
      ],
      seqs2: [
        {
          seq: 'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATCATCATATACTCATTTTTACATCATC-AT',
          metadata: [
            {
              color: 'orange',
              positions: [
                [1, 5],
                [20, 30]
              ]
            },
            {
              color: 'yellow',
              positions: [[6, 19]]
            }
          ]
        },
        {
          seq: 'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATCATCATATACTCATTTTTACATCATCATC',
          metadata: [
            {
              color: 'orange',
              positions: [
                [1, 5],
                [25, 30]
              ]
            },
            {
              color: 'yellow',
              positions: [[6, 19]]
            }
          ]
        }
      ],
      tracks: [],
      testTracks: [
        {
          features: [
            {
              positions: [
                [1, 20],
                [109, 130]
              ],
              type: 'label1',
              color: 'green'
            },
            {
              positions: [[21, 108]],
              type: 'label2',
              color: 'pink'
            }
          ],
          trackLabel: 'label1/label2'
        }
      ],
      coloring: 'metadata' //'auto'
    };
  }
};
</script>
