<template>
  <div id="app">
    <svg-msa :seqs="seqs2" coloring="auto"></svg-msa>
    <svg-msa
      :start="start"
      :end="end"
      :seqs="testSeqs"
      :tracks="testTracks"
      coloring="seqcolor"
      :selectedseqs="selectedseqid"
      :metadatas="metadatas"
    ></svg-msa>
  </div>
</template>

<script>
import SvgMsa from './components/SvgMsa/SvgMsa.vue';

export default {
  name: 'App',
  components: {
    SvgMsa
  },
  data() {
    return {
      start: 58,
      end: -1,
      selectedseqid: ['seqid1', 'seqid2', 'seqid5'],
      metadatas: [
        {
          label: 'conservation level',
          values: [
            {
              label: 'high level',
              fill: 'blue',
              fillopacity: 0.3
            },
            {
              label: 'moderate level',
              fill: 'pink',
              fillopacity: 0.8
            }
          ]
        },
        {
          label: 'drought resistance',
          values: [
            { label: 'high', stroke: 'green', strokedash: true },
            { label: 'weak', stroke: 'blue', strokedash: false }
          ]
        }
      ],

      seqs2: [
        {
          seq: 'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATCATCATATACTCATTTTTACATCATC-AT',
          seqid: 's1',
          isNode: true,
          isConsensus: true
        },
        {
          seq: 'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATCATCATATACTCATTTTTACATCATCATC',
          seqid: 's2',
          isNode: false,
          isConsensus: false
        }
      ],

      testSeqs: [
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACAGCAGCCCTTACGACGATTTACGCGAGAACACTATCATCACAGACGAATTAGAGAGGGGGACAGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACTCACAGCATACGATGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCAAT',
          id: 'seq1',
          name: 'seq1',
          color: 'red',
          metadatas: [
            {
              id: 0,
              value_id: 0,
              ranges: [
                [1, 40],
                [100, 234]
              ]
            },
            { id: 0, value_id: 1, ranges: [[41, 99]] },
            { id: 1, value_id: 0 }
          ]
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACAGCAGCCCTTACGACGATTTACGCGAGAACACTATCATCACAGACGAATTAGAGAGGGGGACAGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACTCACAGCATAC----ACACAGACGACGACAGCAGTCGACGTTTCATATACTCA---TTACATCATCAAT',
          id: 'seq2',
          name: 'seq2',
          color: 'red'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACAGCAGCCC-GACG--GATTTACGCGAGAACACTATCATCACAGACGAATTAGAGAGGGGGACAGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACTCACAGCATACGATGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCAAT',
          id: 'seq3',
          name: 'seq3',
          color: 'red'
        },
        {
          seq:
            'ATCATCATCATCATGGTACTCA---TTACATCATCATCATACTACATGACGACGACAGCAGCCCTTACGACGATTTACGCGAGAACACTATCATCACAGACGAATT------------AGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACTCACAGCATACGATGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCAAT',
          id: 'seq4',
          name: 'seq4',
          color: 'blue'
        },
        {
          seq:
            'ATCATCATCATCATGGTACTCATTTTTACATCATCATCATACTACATGACGACGACAGCAGCCCTTACGACGATTTACGCGAGAACACTATCATCACAGACGAATT------------AGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACTCACAGCATACGATGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCAAT',
          id: 'seq5',
          name: 'seq5',
          color: 'blue'
        },
        {
          seq:
            '--------------------CATTTTTACATCATCATCATACTACATGACGACGACAGCAGCCCTTACGACGATTTACGCGAGAACACTATCATCACAGACGAATTAGAGAGGGGGACAGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACTCACAGCATACGATGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCAAT',
          id: 'seq6',
          name: 'seq6',
          color: 'green'
        },
        {
          seq:
            '--------------------CATTTTTACATCATCATCATACTACATGACGACGACAGCAGCCCTTACGACGATTTACGCGAGAACACTATCATCACAGACGAATTAGAGAGGGGGACAGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACTCACAGCATACGATGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCAAT',
          id: 'seq7',
          name: 'seq7',
          color: 'green'
        },
        {
          seq:
            '--------------------CATTTTTACATCATCATCATACTACATGACGACGACAGCAGCCCTTACGACGATTTACGCGAGAACACTATCATCACAGACGAA----------GGACAGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACCCACAGCATACGATGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCAGGAAT',
          name: 'seq8',
          color: 'green'
        },
        {
          seq:
            '--------------------CATTTTTACATCATCATCATACTACATGACGACGACAGCAGCCCTTACGACGATTTACGCGAGAACACTATCATCACAGACGAATTAGA-----GGACAGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACTCACAGCATACGATGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCAAT',
          id: 'seq9',
          name: 'seq9',
          color: 'green'
        },
        {
          seq:
            '--------------------CATTTTTACATCATCATCATACTACATGACGACGACAGCAGCCCTTACGACGATTTACGCGAGAACACTATCATCACAGACGAATTAGAGA---TGACAGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACTCACAGCATACGATGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCAAT',
          id: 'seq10',
          name: 'seq10',
          color: 'green'
        },
        {
          seq:
            '--------------------CATTTTTACATCATTATCATACTACATGACGACGACAGCAGCCCTTACGACGATTTACGCGAGAACACTATCATCACAGACGAATTAGAGA---T-TCAGAGGGACAGCAGCAGCCCAGACAGACGACCCGATTTATACTCATACTCACAGCATACGATGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCAAT',
          id: 'seq11',
          name: 'seq11',
          color: 'green'
        }
      ],
      seqs: [
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC-AT',
          id: 'seqid1',
          name: 'seq1'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC',
          id: 'seqid2',
          name: 'seq2'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC-AT',
          id: 'seqid3',
          name: 'seq3'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC',
          id: 'seqid4',
          name: 'seq4'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC-AT',
          id: 'seqid5',
          name: 'seq5'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC',
          id: 'seqid6',
          name: 'seq6'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATC-AT',
          id: 'seqid7',
          name: 'seq7'
        },
        {
          seq:
            'ATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCACGCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCATCATCATCATCATCATACTCATTTTTACATCATCATCATACTACATGACGACGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGCAGACGAAAAGGGGGGGGGGGGGGGGGGGGGGGACACAGACGACGACAGCAGACGACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATCACGCATCATATACTCATTTTTACATCATC',
          id: 'seqid8',
          name: 'seq8'
        }
      ],
      tracks: [],
      testTracks: [
        {
          features: [
            {
              positions: [
                [1, 20],
                [109, 234]
              ],
              type: 'label1',
              color: 'green'
            },
            {
              positions: [[21, 108]],
              type: 'label2',
              color: 'pink'
            }
          ],
          trackLabel: 'label1/label2'
        }
      ],
      coloring: 'auto' //'auto'
    };
  }
};
</script>
